# YORHA_MAIN_CONFIG
# Yorha Hyprland entry configuration
$yorha = $HOME/.config/hypr/themes/yorha
$mainMod = SUPER

monitor = , preferred, auto, 1

input {
    kb_layout = us
    follow_mouse = 1
    touchpad {
        natural_scroll = no
    }
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}

exec-once = /usr/lib/polkit-kde-authentication-agent-1

bind = $mainMod, Q, exec, kitty
bind = $mainMod, RETURN, exec, footclient
bind = $mainMod, C, killactive
bind = $mainMod, V, togglefloating
bind = $mainMod, F, fullscreen
bind = $mainMod, M, exit
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9

source = $yorha/theme.conf
